// Generated by build/gen.py but checked-in manually
// Because build/gen.py has been configured to not
// produce this file when this package is fetched from NPM
// as over there, .git folder is missing.

#ifndef OUT_LAST_COMMIT_POSITION_H_
#define OUT_LAST_COMMIT_POSITION_H_

#define LAST_COMMIT_POSITION_NUM 2201
#define LAST_COMMIT_POSITION "2201 (feafd1012a32)"

#endif  // OUT_LAST_COMMIT_POSITION_H_
